services:
  - type: static
    name: zion-birthday
    env: static
    branch: main
    autoDeploy: true
    buildCommand: node /opt/render/project/src/build-config.js
    publishPath: ./birthday
    envVars:
      - key: WHATSAPP_NUMBER
        value: 44743960764
      - key: BIRTHDAY_DATE
        value: 07/07
