services:
  - type: static
    name: zion-birthday
    env: static
    branch: main
    autoDeploy: true
    buildCommand: node ./birthday/build-config.js
    publishPath: ./birthday
    envVars:
      - key: WHATSAPP_NUMBER
        value: 256743960764
      - key: BIRTHDAY_DATE
        value: 08/07
